"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ui.py']
OPTIONS = {
    'resources':'r0capture',
}

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=['requests','frida','hexdump','PyQt5'],
)
